Modulo
ErykPiasecki07/VerbCalc pull request #35
Opened 2021-11-13 16:14 UTC by MaximeJdDS

We can now write '2 mod 2' to compute the modulo 2 of 2 ( works with the word 'modulo' too ).
I tried to follow the code style as much as possible. Hoping is enough. 

Happy coding :D

2021-11-13 20:49 UTC, ErykPiasecki07 requested changes
Hi! Great job, there's only one thing left, you named the setter 'logarithm' instead of 'modulo' (or I am just bad at math and there's some correlation I don't see ;) )

2021-11-13 20:49 UTC, ErykPiasecki07 commented on verbcalc/core/translator/symbols.py
> +    def logarithm(self, value) -> None:
Shouldn't it be called modulo?

2021-11-13 20:52 UTC, ErykPiasecki07 commented on verbcalc/core/translator/symbols.py
> +    def logarithm(self, value) -> None:
Oh, and by the way, there's something called linked issues on GitHub pull requests. If you type in your PR's description: 'Resolves #31' (or `#` followed by any issue number), GitHub will treat both as directly related, so when the pull request gets merged, the issue will close automatically ;)

2021-11-14 00:48 UTC, MaximeJdDS commented on verbcalc/core/translator/symbols.py
> +    def logarithm(self, value) -> None:
Yes ! For sure ! It a residual of my previous idea, sorry...

Have a sweet sunday. :)

2021-11-15 17:10 UTC, ErykPiasecki07 approved these changes

2021-11-15 17:11 UTC, merged

2021-11-25 00:01 UTC, ErykPiasecki07 commented
Hi @MaximeJdDS!
I forgot to create the AUTHORS.MD file at the beginning of repo's life, so if you wanna be listed for your contribution, let me know with an email of yours.

Have a nice day!