added question sentences
ErykPiasecki07/VerbCalc pull request #46
Opened 2021-11-24 09:11 UTC by syedatif4118

I have added some new question sentences! Please check out and if there is any issue please let me know

2021-11-24 09:52 UTC, ErykPiasecki07 requested changes

2021-11-24 09:52 UTC, ErykPiasecki07 commented on verbcalc/core/translator/symbols.py
> +        self._questions = ['what is the result of', 'what is', 'calculate', 'when','if', 'result of','addition of','how do you','find','how much','how much is', 'which number is result of', 'subtract
Great job, however there are some words that we have to be careful using. 'When' and 'if' are logical connectives and have some deeper meaning that has to be handled separately. I would also opt out from 'addition of', and 'subtraction of', as they suggest the operation that will not be further translated to any symbol. The rest however is very good!
```suggestion
        self._questions = ['what is the result of', 'what is', 'calculate', 'result of', 'how do you', 'find',' how much', 'how much is', 'which number is result of', 'what' ]
```

2021-11-24 09:54 UTC, ErykPiasecki07 approved these changes

2021-11-24 09:54 UTC, merged

2021-11-24 10:29 UTC, syedatif4118 commented
OK, thanks a lot for letting me contribute to your project. I hope I was helpful.
Can you please let me know if there are any other issues where I can contribute? 
Which will help me enhance my skills plus help in more contributions.

2021-11-25 18:20 UTC, ErykPiasecki07 commented
Great to see you coming back!
All the issues that don't have assignee are free to take! 

Have a nice day!

2021-11-25 18:22 UTC, ErykPiasecki07 commented
By the way, feel free to add yourself to the recently created AUTHORS.md file! I think contributors like You should be appreciated for their work!

2021-11-25 18:52 UTC, syedatif4118 commented
Yh sure I will check out the issues and let you know!!